### ISSUE TITLE
tables prefix support

### ISSUE THREAD

**Issue by EhabAmawi** [enanobots/m2-m1migration#2]
it would be awsome this module supports database tables prefix, where I tried it on my store and it fails to find the tables, due prefixing

**Comment by enanobots** [comment]
@EhabAmawi  thanks for this.
In all our work we have not worked in any project with database prefixes :-)

**Comment by enanobots** [comment]
https://github.com/enanobots/m2-m1migration/pull/3

**Comment by enanobots** [comment]
Code merged
